services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  scraper:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
      - minio
    volumes:
      - ./audios:/app/audios
    command: ["python", "scraper.py"]
  retry:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
      - minio
    volumes:
      - ./audios:/app/audios
    command: ["python", "retry_failed.py"]
  azure-sync:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
      - minio
    volumes:
      - ./audios:/app/audios
    command: ["python", "azure_sync.py"]

volumes: 
  mongo_data:
  minio_data: